### ISSUE TITLE
check if we can get rid of the fsGroup config in the Helm chart

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-x-helm#11]
You currently have to set the fsGroup to 0 when running the Helm chart on K8s. People tend to forget that. However, we don't need to this for the subcharts. So I guess there is a way around it. We should check how our subcharts are handling this and then handle it the same way.

**Comment by alwx** [comment]
I deployed the helm chart to both minikube and my GKE cluster and set the following `securityContext` settings: 

```
securityContext:
  runAsUser: 1000
  fsGroup: 1000
```

From what I see, everything works perfectly fine, and the PersistentVolumeClaim is accessible. Here is my log:

```
➜  rasa-x git:(master) ✗ kubectl get pods
NAME                                                READY   STATUS             RESTARTS   AGE
chart-1580388764-app-6b765f65f9-46j8h               1/1     Running            0          12m
chart-1580388764-duckling-5b59fc7b-ztwrn            0/1     CrashLoopBackOff   2          47s
chart-1580388764-event-service-557fc746fc-mcr5h     1/1     Running            3          12m
chart-1580388764-nginx-6dc847df85-rwmts             1/1     Running            0          12m
chart-1580388764-postgresql-0                       1/1     Running            0          12m
chart-1580388764-rabbit-0                           1/1     Running            0          12m
chart-1580388764-rasa-production-6857cbbd85-xxbk4   1/1     Running            1          12m
chart-1580388764-rasa-worker-7bc65db454-kq9tn       1/1     Running            1          12m
chart-1580388764-rasa-x-8679df69d7-hz22c            1/1     Running            2          12m
chart-1580388764-redis-master-0                     1/1     Running            0          12m
➜  rasa-x git:(master) ✗ kubectl get pvc
NAME                                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
chart-1580388764-rasa-x-claim                Bound    pvc-76651796-435f-11ea-b28a-42010a8401ec   10Gi       RWO            standard       12m
data-chart-1580388764-postgresql-0           Bound    pvc-77c624e9-435f-11ea-b28a-42010a8401ec   8Gi        RWO            standard       12m
data-chart-1580388764-rabbit-0               Bound    pvc-77454b6b-435f-11ea-b28a-42010a8401ec   8Gi        RWO            standard       12m
redis-data-chart-1580388764-redis-master-0   Bound    pvc-779d0e2e-435f-11ea-b28a-42010a8401ec   8Gi        RWO            standard       12m
➜  rasa-x git:(master) ✗ kubectl exec -it chart-1580388764-rasa-x-8679df69d7-hz22c -- cat /app/environments.yml
rasa:
  production:
    url: "http://chart-1580388764-rasa-x-rasa-production:5005"
    token: ${RASA_TOKEN}
  worker:
    url: "http://chart-1580388764-rasa-x-rasa-worker:5005"
    token: ${RASA_TOKEN}
```

**Comment by wochinge** [comment]
Can you try uploading a model? And try to explicitly not to set it at all.

**Comment by alwx** [comment]
Experienced no problems uploading a model.

Logs:
```
[2020-01-30 16:40:29 +0000] - (sanic.access)[INFO][10.4.1.5:57512]: POST http://35.187.75.126/api/projects/default/models?api_token=18a4f51bf8a6b5e805a090294790bca204d4c11a  204 0
```

```
➜  rasa-x git:(master) ✗ kubectl exec -it chart-1580402156-rasa-x-856dffbbbc-wxndx -- ls /app/models
model.tar.gz
```

**Comment by wochinge** [comment]
This is weird. I'll also try it and come back to you.

**Comment by alwx** [comment]
However, it doesn't work when I don't set it explicitly. 
In this case, `curl` to upload a model gives 500

```
[2020-01-30 16:47:47 +0000] [24] [ERROR] Exception occurred while handling uri: 'http://35.187.75.126/api/projects/default/models?api_token=b22f8904f9f55969db5ce8ec297f2bf458e61c38'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "uvloop/loop.pyx", line 1974, in create_connection
  File "uvloop/loop.pyx", line 1951, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 177, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 107, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/models.py", line 57, in upload_model
    minimum_version = await model_service.minimum_compatible_version()
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/model_service.py", line 120, in minimum_compatible_version
    info = await stack_service.status()
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 53, in status
    return await self.stack_endpoint.request(subpath="/version", method="get")
  File "/usr/local/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 146, in request
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host chart-1580402718-rasa-x-rasa-production:5005 ssl:None [Connection refused]```

**Comment by wochinge** [comment]
Yep, we have to check how others are doing it

<img width="921" alt="Screenshot 2020-01-30 at 17 51 10" src="https://user-images.githubusercontent.com/7667273/73471125-29dab100-4389-11ea-9787-be644b3b1c3b.png">

**Comment by alwx** [comment]
In general, I think setting `fsGroup` to `0` is something we should avoid doing, but we definitely can set the `securityContext` to something like I've shown above.
I see others also do this (see the examples from here: https://github.com/helm/charts) + they allow you to override the security context if you want to.

**Comment by wochinge** [comment]
Ah, okay, they just set a default (referring to the postgres chart)

```
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
```

**Comment by alwx** [comment]
Others set it to something like that:
- https://github.com/helm/charts/blob/master/stable/keycloak/values.yaml#L29

**Comment by alwx** [comment]
@wochinge it works with OpenShift as well

**Comment by wochinge** [comment]
Cool 🎉 Can you create a PR please?

**Comment by alwx** [comment]
Done!
